/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthLayoutRouteImport } from './routes/_auth/_layout'
import { Route as AuthLayoutIndexRouteImport } from './routes/_auth/_layout/index'
import { Route as AuthLayoutProductsRouteImport } from './routes/_auth/_layout/products'
import { Route as AuthLayoutOrdersRouteImport } from './routes/_auth/_layout/orders'
import { Route as AuthLayoutCustomersRouteImport } from './routes/_auth/_layout/customers'
import { Route as AuthLayoutProductsCreateRouteImport } from './routes/_auth/_layout/products_.create'
import { Route as AuthLayoutProductsIdViewRouteImport } from './routes/_auth/_layout/products_.$id.view'
import { Route as AuthLayoutProductsIdEditRouteImport } from './routes/_auth/_layout/products_.$id.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLayoutIndexRoute = AuthLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutProductsRoute = AuthLayoutProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutOrdersRoute = AuthLayoutOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutCustomersRoute = AuthLayoutCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutProductsCreateRoute =
  AuthLayoutProductsCreateRouteImport.update({
    id: '/products_/create',
    path: '/products/create',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutProductsIdViewRoute =
  AuthLayoutProductsIdViewRouteImport.update({
    id: '/products_/$id/view',
    path: '/products/$id/view',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutProductsIdEditRoute =
  AuthLayoutProductsIdEditRouteImport.update({
    id: '/products_/$id/edit',
    path: '/products/$id/edit',
    getParentRoute: () => AuthLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/customers': typeof AuthLayoutCustomersRoute
  '/orders': typeof AuthLayoutOrdersRoute
  '/products': typeof AuthLayoutProductsRoute
  '/': typeof AuthLayoutIndexRoute
  '/products/create': typeof AuthLayoutProductsCreateRoute
  '/products/$id/edit': typeof AuthLayoutProductsIdEditRoute
  '/products/$id/view': typeof AuthLayoutProductsIdViewRoute
}
export interface FileRoutesByTo {
  '/customers': typeof AuthLayoutCustomersRoute
  '/orders': typeof AuthLayoutOrdersRoute
  '/products': typeof AuthLayoutProductsRoute
  '/': typeof AuthLayoutIndexRoute
  '/products/create': typeof AuthLayoutProductsCreateRoute
  '/products/$id/edit': typeof AuthLayoutProductsIdEditRoute
  '/products/$id/view': typeof AuthLayoutProductsIdViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/_layout': typeof AuthLayoutRouteWithChildren
  '/_auth/_layout/customers': typeof AuthLayoutCustomersRoute
  '/_auth/_layout/orders': typeof AuthLayoutOrdersRoute
  '/_auth/_layout/products': typeof AuthLayoutProductsRoute
  '/_auth/_layout/': typeof AuthLayoutIndexRoute
  '/_auth/_layout/products_/create': typeof AuthLayoutProductsCreateRoute
  '/_auth/_layout/products_/$id/edit': typeof AuthLayoutProductsIdEditRoute
  '/_auth/_layout/products_/$id/view': typeof AuthLayoutProductsIdViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/customers'
    | '/orders'
    | '/products'
    | '/'
    | '/products/create'
    | '/products/$id/edit'
    | '/products/$id/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/customers'
    | '/orders'
    | '/products'
    | '/'
    | '/products/create'
    | '/products/$id/edit'
    | '/products/$id/view'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth/_layout'
    | '/_auth/_layout/customers'
    | '/_auth/_layout/orders'
    | '/_auth/_layout/products'
    | '/_auth/_layout/'
    | '/_auth/_layout/products_/create'
    | '/_auth/_layout/products_/$id/edit'
    | '/_auth/_layout/products_/$id/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_layout': {
      id: '/_auth/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_layout/': {
      id: '/_auth/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/products': {
      id: '/_auth/_layout/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthLayoutProductsRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/orders': {
      id: '/_auth/_layout/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthLayoutOrdersRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/customers': {
      id: '/_auth/_layout/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthLayoutCustomersRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/products_/create': {
      id: '/_auth/_layout/products_/create'
      path: '/products/create'
      fullPath: '/products/create'
      preLoaderRoute: typeof AuthLayoutProductsCreateRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/products_/$id/view': {
      id: '/_auth/_layout/products_/$id/view'
      path: '/products/$id/view'
      fullPath: '/products/$id/view'
      preLoaderRoute: typeof AuthLayoutProductsIdViewRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/products_/$id/edit': {
      id: '/_auth/_layout/products_/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof AuthLayoutProductsIdEditRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutCustomersRoute: typeof AuthLayoutCustomersRoute
  AuthLayoutOrdersRoute: typeof AuthLayoutOrdersRoute
  AuthLayoutProductsRoute: typeof AuthLayoutProductsRoute
  AuthLayoutIndexRoute: typeof AuthLayoutIndexRoute
  AuthLayoutProductsCreateRoute: typeof AuthLayoutProductsCreateRoute
  AuthLayoutProductsIdEditRoute: typeof AuthLayoutProductsIdEditRoute
  AuthLayoutProductsIdViewRoute: typeof AuthLayoutProductsIdViewRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutCustomersRoute: AuthLayoutCustomersRoute,
  AuthLayoutOrdersRoute: AuthLayoutOrdersRoute,
  AuthLayoutProductsRoute: AuthLayoutProductsRoute,
  AuthLayoutIndexRoute: AuthLayoutIndexRoute,
  AuthLayoutProductsCreateRoute: AuthLayoutProductsCreateRoute,
  AuthLayoutProductsIdEditRoute: AuthLayoutProductsIdEditRoute,
  AuthLayoutProductsIdViewRoute: AuthLayoutProductsIdViewRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface AuthRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
